require_relative "symbol_table"
require_relative "terminals"
require_relative "intermediate/errors"
require_relative "intermediate/program"
require_relative "intermediate/class"
require_relative "intermediate/field"
require_relative "intermediate/method"
require_relative "intermediate/formal"
require_relative "intermediate/procedure"
require_relative "intermediate/statements"
require_relative "intermediate/expression"
require_relative "intermediate/prefix_expr"
require_relative "intermediate/infix_expr"
require_relative "intermediate/null_expr"
require_relative "intermediate/method_call_expr"
require_relative "intermediate/id_expr"
require_relative "intermediate/init_expr"
require_relative "intermediate/this_expr"
require_relative "intermediate/int_literal_expr"
require_relative "intermediate/boolean_literal_expr"
require_relative "intermediate/continue_label_helper"

module Intermediate
end
